 version: 2

 # schema.yml



 sources:
   - name: raw
     identifier: gz_raw_data
   
     tables:
       - name: sales 
         identifier: raw_gz_sales
       - name: raw_gz_product
         identifier: raw_gz_product
       - name: ship
         identifier: raw_gz_ship